# Generated by Django 5.1.2 on 2024-11-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('second_name', models.TextField()),
                ('war_nik', models.TextField()),
                ('wound_type', models.TextField()),
                ('wound_case', models.TextField()),
                ('avatar', models.ImageField(default='default_avatar.png', upload_to='profile_images')),
            ],
        ),
    ]
