# Generated by Django 5.1.2 on 2025-03-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior', '0002_warrior_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='sum_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrior',
            name='sum_raised',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrior',
            name='wound_date',
            field=models.DateField(default='2022-02-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrior',
            name='wound_location',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
