# Generated by Django 5.1.2 on 2025-03-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior', '0003_warrior_sum_amount_warrior_sum_raised_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrior',
            name='sum_raised',
            field=models.IntegerField(default=0),
        ),
    ]
